change sftp method to clone

diff --git a/configScript b/configScript
--- a/configScript
+++ b/configScript
@@ -31,6 +31,21 @@ while getopts "12" opt; do
   esac
 done
 
+# It will install packages.
+#   - neovim
+#   - nginx
+#   - tree
+pacman -Syu --noconfirm > /dev/null
+pacman -S --noconfirm neovim > /dev/null || { echo "neovim install failed!"; exit 1; }
+pacman -S --noconfirm nginx > /dev/null || { echo "nginx install failed!"; exit 1; }
+pacman -S --noconfirm tree > /dev/null || { echo "tree install failed!"; exit 1; }
+pacman -Syu --noconfirm > /dev/null
+echo "packages installed!"
+
+# change time zone
+timedatectl set-timezone America/Vancouver
+echo "timezone has changed!"
+
 # create system user webgen with a home directory at `/var/lib/webgen` and as a non-login user.
 useradd -r -m -d /var/lib/webgen -s /usr/sbin/nologin webgen || { echo "adding system user webgen failed!"; exit 1; }
 # create directories
@@ -39,23 +54,24 @@ mkdir /var/lib/webgen/bin /var/lib/webgen/HTML /var/lib/webgen/documents || { ec
 echo "hello this is file one from server ${server}" > /var/lib/webgen/documents/file-one || { echo "creating files failed!"; exit 1; }
 echo "hello this is file two from server ${server}" > /var/lib/webgen/documents/file-two || { echo "creating files failed!"; exit 1; }
 # move `generate_index` to the `/var/lib/webgen/bin`
-mv ./packages/generate_index /var/lib/webgen/bin || { echo "moving generate_index failed!"; exit 1; }
+mv ~/linux-assignment3-part2/packages/generate_index /var/lib/webgen/bin || { echo "moving generate_index failed!"; exit 1; }
 # change the permission of generate_index
 chmod +x /var/lib/webgen/bin/generate_index || { echo "changing permission of generate_index failed!"; exit 1; }
 # change ownership to user webgen
 chown -R webgen:webgen /var/lib/webgen/ || { echo "changing ownership failed!"; exit 1; }
 # Move a service file service and timer and nginx.conf
-mv ./packages/generate_index.service /etc/systemd/system/generate_index.service || { echo "moving service failed!"; exit 1; }
-mv ./packages/generate_index.timer /etc/systemd/system/generate_index.timer || { echo "moving timer failed!"; exit 1; }
-mv ./packages/nginx.conf /etc/nginx/nginx.conf || { echo "moving nginx.conf failed!"; exit 1; }
+mv ~/linux-assignment3-part2/packages/generate_index.service /etc/systemd/system/generate_index.service || { echo "moving service failed!"; exit 1; }
+mv ~/linux-assignment3-part2/packages/generate_index.timer /etc/systemd/system/generate_index.timer || { echo "moving timer failed!"; exit 1; }
+mv ~/linux-assignment3-part2/packages/nginx.conf /etc/nginx/nginx.conf || { echo "moving nginx.conf failed!"; exit 1; }
 # create directories for management
 mkdir /etc/nginx/sites-available /etc/nginx/sites-enabled || { echo "making directory failed!"; exit 1; }
 # move server block file
-mv ./packages/webgen.conf /etc/nginx/sites-available/webgen.conf || { echo "moving webgen.conf failed!"; exit 1; }
+mv ~/linux-assignment3-part2/packages/webgen.conf /etc/nginx/sites-available/webgen.conf || { echo "moving webgen.conf failed!"; exit 1; }
 # enable and start
 ln -s /etc/nginx/sites-available/webgen.conf /etc/nginx/sites-enabled/webgen.conf >/dev/null || { echo "enable server block failed!"; exit 1; }
 systemctl daemon-reload || { echo "damon-reloading failed!"; exit 1; }
 systemctl enable --now generate_index.service || { echo "enable and start service failed!"; exit 1; }
 systemctl enable --now generate_index.timer || { echo "enable and start timer failed!"; exit 1; }
 systemctl start nginx.service || { echo "start nginx failed!"; exit 1; }
+echo
 echo "script finished!"
