update UFW setting

diff --git a/configScript b/configScript
--- a/configScript
+++ b/configScript
@@ -8,46 +8,80 @@ fi
 # It will install packages.
 #   - neovim
 #   - nginx
+#   - ufw
 #   - tree
-pacman -Syu --noconfirm > /dev/null
-pacman -S --noconfirm neovim > /dev/null || { echo "neovim install failed!"; exit 1; }
-pacman -S --noconfirm nginx > /dev/null || { echo "nginx install failed!"; exit 1; }
-pacman -S --noconfirm tree > /dev/null || { echo "tree install failed!"; exit 1; }
-pacman -Syu --noconfirm > /dev/null
-echo "packages installed!"
+if pacman -Syu --noconfirm > /dev/null &&
+    pacman -S --noconfirm neovim > /dev/null &&
+    pacman -S --noconfirm nginx > /dev/null &&
+    pacman -S --noconfirm ufw > /dev/null &&
+    pacman -S --noconfirm tree > /dev/null &&
+    pacman -Syu --noconfirm > /dev/null; then
+    echo "packages instalation success!"
+else
+    { echo "packages instalation failed!"; exit 1; }
+fi
 
 # change time zone
 timedatectl set-timezone America/Vancouver
 echo "timezone has changed!"
 
 # create system user webgen with a home directory at `/var/lib/webgen` and as a non-login user.
-useradd -r -m -d /var/lib/webgen -s /usr/sbin/nologin webgen || { echo "adding system user webgen failed!"; exit 1; }
-# create directories
-mkdir /var/lib/webgen/bin /var/lib/webgen/HTML /var/lib/webgen/documents || { echo "creating directories failed!"; exit 1; }
+if useradd -r -m -d /var/lib/webgen -s /usr/sbin/nologin webgen &&
+    mkdir /var/lib/webgen/bin /var/lib/webgen/HTML /var/lib/webgen/documents; then
+        echo "system user 'webgen' has been created!"
+else
+    { echo "creating system user 'webgen' has failed!"; exit 1; }
+fi
+
 # create files
-echo "hello this is file one" > /var/lib/webgen/documents/file-one || { echo "creating files failed!"; exit 1; }
-echo "hello this is file two" > /var/lib/webgen/documents/file-two || { echo "creating files failed!"; exit 1; }
+if echo "hello this is file one" > /var/lib/webgen/documents/file-one &&
+    echo "hello this is file two" > /var/lib/webgen/documents/file-two; then
+        echo "test files created!"
+else
+    { echo "creating test files has failed!"; exit 1; }
+fi
 
 # move `generate_index` to the `/var/lib/webgen/bin`
-mv ./linux-assignment3-part2/packages/generate_index /var/lib/webgen/bin || { echo "moving generate_index failed!"; exit 1; }
+if mv ./linux-assignment3-part2/packages/generate_index /var/lib/webgen/bin &&
 # change the permission of generate_index
-chmod +x /var/lib/webgen/bin/generate_index || { echo "changing permission of generate_index failed!"; exit 1; }
+    chmod +x /var/lib/webgen/bin/generate_index &&
 # change ownership to user webgen
-chown -R webgen:webgen /var/lib/webgen/ || { echo "changing ownership failed!"; exit 1; }
+    chown -R webgen:webgen /var/lib/webgen/ &&
 # Move a service file service and timer and nginx.conf
-mv ./linux-assignment3-part2/packages/generate_index.service /etc/systemd/system/generate_index.service || { echo "moving service failed!"; exit 1; }
-mv ./linux-assignment3-part2/packages/generate_index.timer /etc/systemd/system/generate_index.timer || { echo "moving timer failed!"; exit 1; }
-mv ./linux-assignment3-part2/packages/nginx.conf /etc/nginx/nginx.conf || { echo "moving nginx.conf failed!"; exit 1; }
+    mv ./linux-assignment3-part2/packages/generate_index.service /etc/systemd/system/generate_index.service &&
+    mv ./linux-assignment3-part2/packages/generate_index.timer /etc/systemd/system/generate_index.timer &&
+    mv ./linux-assignment3-part2/packages/nginx.conf /etc/nginx/nginx.conf &&
 # create directories for management
-mkdir /etc/nginx/sites-available /etc/nginx/sites-enabled || { echo "making directory failed!"; exit 1; }
+    mkdir /etc/nginx/sites-available /etc/nginx/sites-enabled &&
 # move server block file
-mv ./linux-assignment3-part2/packages/webgen.conf /etc/nginx/sites-available/webgen.conf || { echo "moving webgen.conf failed!"; exit 1; }
-# enable and start
-ln -s /etc/nginx/sites-available/webgen.conf /etc/nginx/sites-enabled/webgen.conf >/dev/null || { echo "enable server block failed!"; exit 1; }
-systemctl daemon-reload || { echo "damon-reloading failed!"; exit 1; }
-systemctl enable --now generate_index.service || { echo "enable and start service failed!"; exit 1; }
-systemctl enable --now generate_index.timer || { echo "enable and start timer failed!"; exit 1; }
-systemctl start nginx.service || { echo "start nginx failed!"; exit 1; }
+    mv ./linux-assignment3-part2/packages/webgen.conf /etc/nginx/sites-available/webgen.conf; then
+        echo "configuration files moved!"
+else
+    { echo "moving config files failed!"; exit 1; }
+fi
+# enabling config files
+if ln -s /etc/nginx/sites-available/webgen.conf /etc/nginx/sites-enabled/webgen.conf >/dev/null &&
+systemctl daemon-reload &&
+systemctl enable --now generate_index.service &&
+systemctl enable --now generate_index.timer &&
+systemctl start nginx.service; then
+    echo "configuration flies enabled!"
+else
+    { echo "failed to enable configuration flies!"; exit 1; }
+fi
+
+# ufw setting
+if ufw allow ssh && 
+   ufw allow http && 
+   ufw limit ssh && 
+   systemctl enable --now ufw.service && 
+   echo "y" | ufw enable; then
+    echo "ufw setting success!"
+else
+    
+    { echo "ufw setting failed!"; exit 1; }
+fi
+
 echo
 echo "script finished!"
 echo
