bug fix

diff --git a/configScript b/configScript
--- a/configScript
+++ b/configScript
@@ -18,7 +18,8 @@ if pacman -Syu --noconfirm > /dev/null &&
     pacman -Syu --noconfirm > /dev/null; then
     echo "packages instalation success!"
 else
-    { echo "packages instalation failed!"; exit 1; }
+    echo "packages instalation failed!"
+    exit 1
 fi
 
 # change time zone
@@ -30,7 +31,8 @@ if useradd -r -m -d /var/lib/webgen -s /usr/sbin/nologin webgen &&
     mkdir /var/lib/webgen/bin /var/lib/webgen/HTML /var/lib/webgen/documents; then
         echo "system user 'webgen' has been created!"
 else
-    { echo "creating system user 'webgen' has failed!"; exit 1; }
+    echo "creating system user 'webgen' has failed!"
+    exit 1
 fi
 
 # create files
@@ -38,7 +40,8 @@ if echo "hello this is file one" > /var/lib/webgen/documents/file-one &&
     echo "hello this is file two" > /var/lib/webgen/documents/file-two; then
         echo "test files created!"
 else
-    { echo "creating test files has failed!"; exit 1; }
+    echo "creating test files has failed!"
+    exit 1
 fi
 
 # move `generate_index` to the `/var/lib/webgen/bin`
@@ -57,7 +60,8 @@ if mv ./linux-assignment3-part2/packages/generate_index /var/lib/webgen/bin &&
     mv ./linux-assignment3-part2/packages/webgen.conf /etc/nginx/sites-available/webgen.conf; then
         echo "configuration files moved!"
 else
-    { echo "moving config files failed!"; exit 1; }
+    echo "moving config files failed!"
+    exit 1
 fi
 # enabling config files
 if ln -s /etc/nginx/sites-available/webgen.conf /etc/nginx/sites-enabled/webgen.conf >/dev/null &&
@@ -67,19 +71,20 @@ systemctl enable --now generate_index.timer &&
 systemctl start nginx.service; then
     echo "configuration flies enabled!"
 else
-    { echo "failed to enable configuration flies!"; exit 1; }
+    echo "failed to enable configuration flies!"
+    exit 1
 fi
 
 # ufw setting
 if ufw allow ssh && 
    ufw allow http && 
    ufw limit ssh && 
-   systemctl enable --now ufw.service && 
-   echo "y" | ufw enable; then
+   systemctl enable --now ufw.service; then
+    echo "y" | ufw enable
     echo "ufw setting success!"
 else
-    
-    { echo "ufw setting failed!"; exit 1; }
+    echo "ufw setting failed!"
+    exit 1
 fi
 
 echo
